import { useState, useEffect } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import { Stack, TextField, IconButton, Button, Autocomplete, Tooltip, Box, Typography, CircularProgress } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import { isValidIpOrCidr, isValidOrigin } from '@app-utils/ipValidation';
import type { AuthorizedUser } from '@app-types/auth';
import type { ListType } from '@services/ip';
import { apiRequest } from '@services/api';


export interface IpOriginRow {
  key: string;
  ip: string;
  referrer: string;
  user_id: number | null;
  expires_at: string | null;
  entry_origin?: string;
}

let rowCounter = 0;
export function createEmptyRow(): IpOriginRow {
  rowCounter += 1;
  return {
    key: `row-${Date.now()}-${rowCounter}`,
    ip: '',
    referrer: '',
    user_id: null,
    expires_at: null,
  };
}

interface AddIpEntriesRepeaterProps {
  rows: IpOriginRow[];
  onChange: (rows: IpOriginRow[]) => void;
  disabled?: boolean;
  onValidityChange?: (hasErrors: boolean) => void;
  listType: ListType;

  userSelection?: {
    wpUsers: AuthorizedUser[];
    wpUsersLoading: boolean;
    authorizedUserIds: number[];
  };
}

export default function AddIpEntriesRepeater({
  rows, onChange, disabled, onValidityChange, listType, userSelection,
}: AddIpEntriesRepeaterProps): JSX.Element {
  const [errors, setErrors] = useState<Record<string, { ip?: string; referrer?: string }>>({});
  const [currentUserIp, setCurrentUserIp] = useState('');

  const reportValidity = (errs: typeof errors) => {
    onValidityChange?.(Object.values(errs).some((e) => e.ip || e.referrer));
  };

  const updateRow = (key: string, patch: Partial<IpOriginRow>) => {
    onChange(rows.map((r) => (r.key === key ? { ...r, ...patch } : r)));
  };

  const removeRow = (key: string) => {
    onChange(rows.filter((r) => r.key !== key));
    setErrors((prev) => {
      const next = { ...prev };
      delete next[key];
      reportValidity(next);
      return next;
    });
  };

  const addRow = () => onChange([...rows, createEmptyRow()]);

  const fetchUserIp = async () => {
    const data = await apiRequest<{ current_user_ip: string }>('bromate_get_current_user_ip');
    if (data?.current_user_ip) {
      setCurrentUserIp(data?.current_user_ip);
    }
  };

  useEffect(() => {
    fetchUserIp();
  }, [fetchUserIp]);

  const handleAddUserIp = () => {
    if (!currentUserIp) return;

    onChange([...rows, { ...createEmptyRow(), ip: currentUserIp }]);
  };

  const handleIpBlur = (row: IpOriginRow) => {
    const trimmed = row.ip.trim();
    const message = trimmed && !isValidIpOrCidr(trimmed)
      ? __('Invalid IP or CIDR', 'bromate-security-api-firewall')
      : undefined;
    setErrors((prev) => {
      const next = { ...prev, [row.key]: { ...prev[row.key], ip: message } };
      reportValidity(next);
      return next;
    });
  };

  const handleReferrerBlur = (row: IpOriginRow) => {
    const trimmed = row.referrer.trim();
    const message = trimmed && !isValidOrigin(trimmed)
      ? __('Enter a valid origin, e.g. https://app.example.com', 'bromate-security-api-firewall')
      : undefined;
    setErrors((prev) => {
      const next = { ...prev, [row.key]: { ...prev[row.key], referrer: message } };
      reportValidity(next);
      return next;
    });
  };

  return (
    <Stack spacing={1.5}>
      {rows.map((row) => {
        const isAutoGenerated = Boolean(row.entry_origin) && row.entry_origin !== 'manual';
        const rowDisabled = disabled || isAutoGenerated;

        return (
          <Stack key={row.key} spacing={1}>
            <Stack direction="row" spacing={1} alignItems="flex-start">
              <TextField
                label={__('IP / CIDR', 'bromate-security-api-firewall')}
                placeholder="203.0.113.1"
                value={row.ip}
                onChange={(e) => updateRow(row.key, { ip: e.target.value })}
                onBlur={() => handleIpBlur(row)}
                size="small"
                required
                disabled={rowDisabled}
                error={Boolean(errors[row.key]?.ip)}
                helperText={errors[row.key]?.ip}
                sx={{ flex: 1 }}
              />
              <TextField
                label={__('Allowed origin', 'bromate-security-api-firewall')}
                placeholder="https://app.example.com"
                value={row.referrer}
                onChange={(e) => updateRow(row.key, { referrer: e.target.value })}
                onBlur={() => handleReferrerBlur(row)}
                size="small"
                disabled={rowDisabled}
                error={Boolean(errors[row.key]?.referrer)}
                helperText={errors[row.key]?.referrer}
                sx={{ flex: 1 }}
              />
              <TextField
                label={__('Expires at', 'bromate-security-api-firewall')}
                type="datetime-local"
                value={row.expires_at ?? ''}
                onChange={(e) => updateRow(row.key, { expires_at: e.target.value || null })}
                size="small"
                disabled={rowDisabled}
                slotProps={{ inputLabel: { shrink: true } }}
                sx={{ flex: 1, maxWidth:200 }}
              />

               {listType === 'whitelist' && userSelection && (
              <Stack flex={1}>
              <Autocomplete<AuthorizedUser>
                options={userSelection.wpUsers}
                loading={userSelection.wpUsersLoading}
                getOptionLabel={(o) => o.display_name}
                isOptionEqualToValue={(o, v) => o.id === v.id}
                value={userSelection.wpUsers.find((u) => u.id === row.user_id) ?? null}
                onChange={(_, v) => updateRow(row.key, { user_id: v?.id ?? null })}
                disabled={rowDisabled}
                getOptionDisabled={(o) => !userSelection.authorizedUserIds.includes(o.id)}
                disablePortal
                renderOption={(props, option) => {
                  const isAuthorized = userSelection.authorizedUserIds.includes(option.id);
                  const item = (
                    <li {...props} key={option.id}>
                      <Box>
                        <Typography variant="body2" fontWeight={500}>
                          {option.display_name}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          {option.email} · {option.roles.join(', ')}
                        </Typography>
                      </Box>
                    </li>
                  );
                  return isAuthorized ? item : (
                    <Tooltip
                      key={option.id}
                      title={__('Only REST-authorized users can be bound to an IP', 'bromate-security-api-firewall')}
                      placement="right"
                    >
                      <span>{item}</span>
                    </Tooltip>
                  );
                }}
                renderInput={(params) => (
                  <TextField
                    {...params}
                    label={__('Bind to REST authorized user', 'bromate-security-api-firewall')}
                    size="small"
                    slotProps={{
                      input: {
                        ...params.InputProps,
                        endAdornment: (
                          <>
                            {userSelection.wpUsersLoading && <CircularProgress size={16} />}
                            {params.InputProps.endAdornment}
                          </>
                        ),
                      },
                    }}
                  />
                )}
              />
              </Stack>
            )}

              {!disabled && (
                <IconButton onClick={() => removeRow(row.key)} size="small" sx={{ mt: 0.5 }}>
                  <DeleteIcon fontSize="small" />
                </IconButton>
              )}
            </Stack>

           
          </Stack>
        );
      })}
      {!disabled && (
        <Stack direction="row">
          <Button size="small" startIcon={<AddIcon />} onClick={addRow}>
            {__('Add IP', 'bromate-security-api-firewall')}
          </Button>

          {listType === 'whitelist' && (
            <Button variant="text" size="small"startIcon={<AddIcon />} onClick={handleAddUserIp}>
              {__('Add My IP', 'bromate-security-api-firewall')}
            </Button>
          )}
        </Stack>
      )}
    </Stack>
  );
}