import { useState, useEffect } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import { usePortalContainer } from '@contexts/PortalContainerContext';
import type { IpEntry, ListType } from '@services/ip';
import type { AuthorizedUser } from '@app-types/auth';

import {
  Box, Typography, Stack, TextField, Button, Autocomplete,
  Dialog, DialogTitle, DialogContent, DialogActions,
  CircularProgress, FormControlLabel, Radio, RadioGroup, FormLabel, FormControl,
  IconButton, Alert,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import { isValidOrigin } from '@app-utils/ipValidation';

export interface EditIpEntryPayload {
  list_type: ListType;
  referrer: string;
  user_id: number | null;
  expires_at: string | null;
}

interface EditIpEntryDialogProps {
  open: boolean;
  entry: IpEntry | null;
  onSave: (payload: EditIpEntryPayload) => Promise<void>;
  onClose: () => void;
  wpUsers: AuthorizedUser[];
  wpUsersLoading: boolean;
  authorizedUserIds: number[];
}

export default function EditIpEntryDialog({
  open, entry, onSave, onClose, wpUsers, wpUsersLoading, authorizedUserIds,
}: EditIpEntryDialogProps) {
  const portalContainer = usePortalContainer();

  const [listType, setListType] = useState<ListType>('blacklist');
  const [referrer, setReferrer] = useState('');
  const [userId, setUserId] = useState<number | null>(null);
  const [expiresAt, setExpiresAt] = useState<string | null>(null);

  const [referrerError, setReferrerError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const isAutoGenerated = Boolean(entry?.entry_origin) && entry?.entry_origin !== 'manual';

  useEffect(() => {
    if (!open || !entry) return;
    setListType(entry.list_type);
    setReferrer(entry.referrer ?? '');
    setUserId(entry.user_id ?? null);
    setExpiresAt(entry.expires_at ?? null);
    setReferrerError(null);
    setSaveError(null);
    setSaving(false);
  }, [open, entry]);

  const handleReferrerBlur = () => {
    const trimmed = referrer.trim();
    setReferrerError(
      trimmed && !isValidOrigin(trimmed)
        ? __('Enter a valid origin, e.g. https://app.example.com', 'bromate-security-api-firewall')
        : null
    );
  };

  const handleSave = async () => {
    setSaving(true);
    setSaveError(null);
    try {
      await onSave({
        list_type: listType,
        referrer: referrer.trim(),
        user_id: listType === 'whitelist' ? userId : null,
        expires_at: expiresAt?.trim() || null,
      });
    } catch (error) {
      setSaveError(error instanceof Error ? error.message : __('Failed to save entry', 'bromate-security-api-firewall'));
      setSaving(false);
      return;
    }
    setSaving(false);
  };

  return (
    <Dialog container={portalContainer} open={open} onClose={saving ? undefined : onClose} fullWidth maxWidth="xs">
      <DialogTitle>
        {__('Edit IP Entry', 'bromate-security-api-firewall')}
        <IconButton onClick={onClose} sx={{ position: 'absolute', right: '8px', top: '8px', zIndex: 10 }}>
          <CloseIcon fontSize="large" />
        </IconButton>
      </DialogTitle>
      <DialogContent dividers>
        <Stack spacing={2} sx={{ pt: 0.5 }}>
          <TextField
            label={__('IP / CIDR', 'bromate-security-api-firewall')}
            value={entry?.ip ?? ''}
            size="small"
            disabled
            fullWidth
            helperText={__('The IP address cannot be changed. Remove and add a new entry instead.', 'bromate-security-api-firewall')}
          />

          {isAutoGenerated && (
            <Alert severity="info">
              {__('This entry was created automatically and cannot be edited.', 'bromate-security-api-firewall')}
            </Alert>
          )}

          <FormControl disabled={isAutoGenerated}>
            <FormLabel>{__('List', 'bromate-security-api-firewall')}</FormLabel>
            <RadioGroup row value={listType} onChange={(e) => setListType(e.target.value as ListType)}>
              <FormControlLabel value="blacklist" control={<Radio size="small" />} label={__('Blacklist', 'bromate-security-api-firewall')} />
              <FormControlLabel value="whitelist" control={<Radio size="small" />} label={__('Whitelist', 'bromate-security-api-firewall')} />
            </RadioGroup>
          </FormControl>

          <TextField
            label={__('Allowed origin (optional)', 'bromate-security-api-firewall')}
            placeholder="https://app.example.com"
            value={referrer}
            onChange={(e) => setReferrer(e.target.value)}
            onBlur={handleReferrerBlur}
            size="small"
            disabled={isAutoGenerated}
            error={Boolean(referrerError)}
            helperText={referrerError}
            fullWidth
          />

          <TextField
            label={__('Expires at', 'bromate-security-api-firewall')}
            type="datetime-local"
            value={expiresAt ?? ''}
            onChange={(e) => setExpiresAt(e.target.value || null)}
            size="small"
            disabled={isAutoGenerated}
            fullWidth
            slotProps={{ inputLabel: { shrink: true } }}
          />

          {listType === 'whitelist' && (
            <Autocomplete<AuthorizedUser>
              options={wpUsers}
              loading={wpUsersLoading}
              getOptionLabel={(o) => o.display_name}
              isOptionEqualToValue={(o, v) => o.id === v.id}
              value={wpUsers.find((u) => u.id === userId) ?? null}
              onChange={(_, v) => setUserId(v?.id ?? null)}
              disabled={isAutoGenerated}
              getOptionDisabled={(o) => !authorizedUserIds.includes(o.id)}
              disablePortal
              renderOption={(props, option) => (
                <li {...props} key={option.id}>
                  <Box>
                    <Typography variant="body2" fontWeight={500}>
                      {option.display_name}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {option.email} · {option.roles.join(', ')}
                    </Typography>
                  </Box>
                </li>
              )}
              renderInput={(params) => (
                <TextField
                  {...params}
                  label={__('Bind to REST authorized user (optional)', 'bromate-security-api-firewall')}
                  size="small"
                  slotProps={{
                    input: {
                      ...params.InputProps,
                      endAdornment: (
                        <>
                          {wpUsersLoading && <CircularProgress size={16} />}
                          {params.InputProps.endAdornment}
                        </>
                      ),
                    },
                  }}
                />
              )}
            />
          )}

          {saveError && (
            <Alert severity="error" variant="outlined">
              <Typography variant="body2">{saveError}</Typography>
            </Alert>
          )}
        </Stack>
      </DialogContent>
      <DialogActions sx={{ color: 'text.secondary' }}>
        <Button onClick={onClose} disableElevation color="inherit" disabled={saving}>
          {__('Cancel', 'bromate-security-api-firewall')}
        </Button>
        <Button
          onClick={handleSave}
          variant="contained"
          disableElevation
          disabled={saving || isAutoGenerated || Boolean(referrerError)}
          startIcon={saving ? <CircularProgress size={14} color="inherit" /> : undefined}
        >
          {saving ? __('Saving…', 'bromate-security-api-firewall') : __('Save', 'bromate-security-api-firewall')}
        </Button>
      </DialogActions>
    </Dialog>
  );
}